'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useAuth } from '@/components/providers/AuthProvider'

type Integration = { id: number; name: string; status: string; description?: string; details?: Record<string, string> }

export function IntegrationCenter() {
  const { token } = useAuth(); const [items, setItems] = useState<Integration[]>([]); const [form, setForm] = useState({ name: '', provider: 'traccar', endpoint: '', credential: '' }); const [message, setMessage] = useState('')
  const load = async () => { const response = await fetch('/api/v1/resources/integrations', { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setItems(await response.json()) }
  useEffect(() => { if (token) void load() }, [token])
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/v1/resources/integrations', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ name: form.name, status: 'configured', description: `${form.provider} integration`, details: { provider: form.provider, endpoint: form.endpoint, credential_configured: form.credential ? 'yes' : 'no' } }) }); setMessage(response.ok ? 'Integration saved.' : ((await response.json().catch(() => null))?.detail ?? 'Could not save integration')); if (response.ok) { setForm({ name: '', provider: 'traccar', endpoint: '', credential: '' }); await load() } }
  const remove = async (id: number) => { await fetch(`/api/v1/resources/integrations/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); await load() }
  return <section><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-forest">Platform</p><h1 className="text-3xl font-bold tracking-tight">Integrations</h1><p className="mt-2 text-slate-500">Connect telematics, maps, finance, ERP, payroll, and webhooks.</p></div><div className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-panel"><h2 className="text-lg font-bold">Add connection</h2><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">Connection name<input className="mt-2 w-full rounded-xl border border-slate-200 p-3" required placeholder="Fleet telematics" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm font-semibold">Provider<select className="mt-2 w-full rounded-xl border border-slate-200 p-3" value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })}><option value="traccar">Traccar</option><option value="google-maps">Google Maps</option><option value="webhook">Custom webhook</option><option value="erp">ERP</option><option value="payroll">Payroll</option></select></label><label className="block text-sm font-semibold">Endpoint URL<input className="mt-2 w-full rounded-xl border border-slate-200 p-3" type="url" placeholder="https://..." value={form.endpoint} onChange={e => setForm({ ...form, endpoint: e.target.value })} /></label><label className="block text-sm font-semibold">Credential<input className="mt-2 w-full rounded-xl border border-slate-200 p-3" type="password" placeholder="Stored securely by the provider" value={form.credential} onChange={e => setForm({ ...form, credential: e.target.value })} /></label>{message && <p className="rounded-xl bg-mist p-3 text-sm text-forest">{message}</p>}<button className="w-full rounded-xl bg-forest p-3 font-bold text-white">Save integration</button></div></form><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-panel"><h2 className="text-lg font-bold">Configured connections</h2><div className="mt-5 space-y-3">{items.map(item => <article className="rounded-xl bg-mist p-4" key={item.id}><div className="flex items-center justify-between"><div><strong>{item.name}</strong><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">{item.details?.provider ?? 'integration'}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-forest">{item.status}</span></div><p className="mt-2 text-sm text-slate-500">{item.details?.endpoint || 'No endpoint configured'}</p><button className="mt-3 text-xs font-bold text-red-600" onClick={() => void remove(item.id)}>Remove</button></article>)}{items.length === 0 && <p className="py-12 text-center text-sm text-slate-400">No integrations configured.</p>}</div></div></div></section>
}
