FROM node:20-alpine AS deps
WORKDIR /workspace
COPY apps/web-console/package.json apps/web-console/package-lock.json ./
RUN npm ci --omit=dev --no-audit --no-fund

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /workspace/node_modules ./node_modules
COPY apps/web-console/package.json ./package.json
COPY apps/web-console/.next ./.next
EXPOSE 3000
CMD ["npm", "run", "start"]
