import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './device.css'

const API = import.meta.env.VITE_API_URL || window.location.origin

async function request(path, options = {}) {
  const token = localStorage.getItem('gps_token')
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'Request failed')
  return response.status === 204 ? null : response.json()
}

const icon = (name) => ({
  grid: '▦', truck: '▰', route: '⌁', shield: '◇', wrench: '⌕', users: '♙', pin: '⌖', bell: '◉', settings: '⚙', search: '⌕', arrow: '↗', check: '✓'
}[name] || '•')

function Auth({ onDone }) {
  const [register, setRegister] = useState(false)
  const [form, setForm] = useState({ email: '', password: '', organization_name: '' })
  const [error, setError] = useState('')
  const submit = async (e) => { e.preventDefault(); setError(''); try { const data = await request(`/api/v1/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('gps_token', data.access_token); onDone() } catch (err) { setError(err.message) } }
  return <main className="auth-shell"><div className="auth-art"><div className="brand large"><span className="brand-mark">✦</span> northstar</div><div className="hero-copy"><p className="eyebrow">COMMAND CENTER / 01</p><h1>Every mile,<br /><em>in view.</em></h1><p>Clarity for the roads that move your business forward.</p></div><div className="orbit"><span /><span /><span /></div><div className="auth-footer">CUSTOM TCP TELEMATICS · REAL-TIME OPERATIONS</div></div><section className="auth-form"><div className="mobile-brand brand"><span className="brand-mark">✦</span> northstar</div><div className="form-intro"><p className="eyebrow">FLEET OPERATIONS PLATFORM</p><h2>{register ? 'Set up your fleet' : 'Welcome back'}</h2><p>{register ? 'Create your workspace to start tracking.' : 'Sign in to your operations command center.'}</p></div><form onSubmit={submit}>{register && <label>Workspace name<input required value={form.organization_name} onChange={e => setForm({ ...form, organization_name: e.target.value })} placeholder="Acme Logistics" /></label>}<label>Work email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Minimum 8 characters" /></label>{error && <div className="error">{error}</div>}<button className="primary wide">{register ? 'Create workspace' : 'Sign in'} <span>→</span></button></form><button className="text-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New to Northstar? Create a workspace'}</button></section></main>
}

function App() {
  const [authed, setAuthed] = useState(!!localStorage.getItem('gps_token'))
  return authed ? <Dashboard onLogout={() => { localStorage.removeItem('gps_token'); setAuthed(false) }} /> : <Auth onDone={() => setAuthed(true)} />
}

function Dashboard({ onLogout }) {
  const [section, setSection] = useState('Overview')
  const [summary, setSummary] = useState({ total_vehicles: 0, online_vehicles: 0, offline_vehicles: 0, open_alerts: 0 })
  const [vehicles, setVehicles] = useState([]); const [positions, setPositions] = useState([]); const [alerts, setAlerts] = useState([]); const [drivers, setDrivers] = useState([]); const [trips, setTrips] = useState([]); const [connected, setConnected] = useState(false)
  const load = async () => { try { const [s, v, a, d, t] = await Promise.all([request('/api/v1/dashboard/summary'), request('/api/v1/vehicles'), request('/api/v1/alerts'), request('/api/v1/drivers'), request('/api/v1/trips')]); setSummary(s); setVehicles(v); setAlerts(a); setDrivers(d); setTrips(t) } catch (e) { if (e.message.includes('authentication')) onLogout() } }
  useEffect(() => { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer) }, [])
  useEffect(() => { const token = localStorage.getItem('gps_token'); if (!token) return; const ws = new WebSocket(`${API.replace('http', 'ws')}/api/v1/ws/live?token=${token}`); ws.onopen = () => setConnected(true); ws.onclose = () => setConnected(false); ws.onmessage = e => setPositions(JSON.parse(e.data).data || []); return () => ws.close() }, [])
  const names = useMemo(() => Object.fromEntries(vehicles.map(v => [v.id, v.name])), [vehicles])
  return <div className="app-shell"><Sidebar section={section} setSection={setSection} onLogout={onLogout} /><main className="main"><header className="topbar"><div><p className="eyebrow">MONDAY · 12 SEPTEMBER 2026</p><h1>{section === 'Overview' ? 'Good morning, operator.' : section}</h1></div><div className="top-actions"><div className="status"><i className={connected ? 'live-dot' : ''} /> {connected ? 'Live link' : 'Reconnecting'}</div><button className="icon-button">{icon('bell')}<b /></button><div className="avatar">OP</div></div></header>{section === 'Overview' ? <Overview summary={summary} vehicles={vehicles} positions={positions} names={names} alerts={alerts} setSection={setSection} connected={connected} /> : <SectionView section={section} vehicles={vehicles} drivers={drivers} trips={trips} alerts={alerts} positions={positions} names={names} reload={load} />}</main></div>
}

function Sidebar({ section, setSection, onLogout }) { const nav = [['Overview', 'grid'], ['Devices', 'truck'], ['Live fleet', 'pin'], ['Trips & dispatch', 'route'], ['Drivers', 'users'], ['Safety', 'shield'], ['Maintenance', 'wrench'], ['Geofences', 'pin']]; return <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span> northstar</div><div className="workspace"><span className="workspace-icon">A</span><span><strong>Atlas Logistics</strong><small>Operations workspace</small></span><span className="chevron">⌄</span></div><nav>{nav.map(([label, i]) => <button className={section === label ? 'active' : ''} key={label} onClick={() => setSection(label)}><span className="nav-icon">{icon(i)}</span>{label}{label === 'Safety' && <em>4</em>}</button>)}</nav><div className="sidebar-bottom"><button><span className="nav-icon">{icon('settings')}</span>Settings</button><button onClick={onLogout}><span className="nav-icon">↪</span>Sign out</button><div className="support"><span>?</span><div><strong>Need a hand?</strong><small>Open support center</small></div></div></div></aside> }

function Overview({ summary, vehicles, positions, names, alerts, setSection, connected }) { return <><div className="stat-grid"><Stat label="Total vehicles" value={summary.total_vehicles} meta="Registered in fleet" tone="blue" /><Stat label="Moving now" value={summary.online_vehicles} meta={`${summary.total_vehicles ? Math.round(summary.online_vehicles / summary.total_vehicles * 100) : 0}% of total fleet`} tone="green" /><Stat label="Offline" value={summary.offline_vehicles} meta="Last 15 minutes" tone="gray" /><Stat label="Open alerts" value={summary.open_alerts} meta="Needs attention" tone="orange" /></div><div className="content-grid"><section className="panel map-panel"><div className="panel-head"><div><p className="eyebrow">LIVE TELEMETRY</p><h2>Fleet overview</h2></div><button className="ghost" onClick={() => setSection('Live fleet')}>Full map <span>↗</span></button></div><FleetMap positions={positions} names={names} connected={connected} /><div className="map-legend"><span><i className="legend moving" /> Moving <b>{summary.online_vehicles}</b></span><span><i className="legend offline" /> Offline <b>{summary.offline_vehicles}</b></span><span className="map-updated">Updated just now</span></div></section><section className="panel alert-panel"><div className="panel-head"><div><p className="eyebrow">ATTENTION NEEDED</p><h2>Latest alerts</h2></div><button className="ghost" onClick={() => setSection('Safety')}>View all</button></div><div className="alert-list">{alerts.length ? alerts.slice(0, 4).map(a => <AlertRow key={a.id} alert={a} />) : <Empty text="No active alerts. Your fleet is looking good." />}</div></section></div><div className="content-grid lower"><section className="panel"><div className="panel-head"><div><p className="eyebrow">ASSET HEALTH</p><h2>Vehicles</h2></div><button className="ghost" onClick={() => setSection('Live fleet')}>View fleet <span>↗</span></button></div><VehicleTable vehicles={vehicles.slice(0, 5)} positions={positions} /></section><section className="panel activity"><div className="panel-head"><div><p className="eyebrow">TODAY</p><h2>Operations pulse</h2></div></div><div className="pulse"><Pulse value={78} label="On-time delivery" color="blue" /><Pulse value={64} label="Fleet utilization" color="green" /><Pulse value={92} label="Driver safety" color="orange" /></div></section></div></> }

function Stat({ label, value, meta, tone }) { return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-arrow">↗</span></div><strong>{value}</strong><small><i />{meta}</small></div> }
function FleetMap({ positions, names, connected }) { return <div className="fleet-map"><div className="map-grid" /><div className="map-label label-a">NORTH DISTRICT</div><div className="map-label label-b">INDUSTRIAL BELT</div><div className="road road-one" /><div className="road road-two" />{positions.slice(0, 10).map((p, i) => <div key={`${p.vehicle_id}-${i}`} className="vehicle-pin" style={{ left: `${18 + ((Math.abs(p.longitude) * 1000) % 68)}%`, top: `${20 + ((Math.abs(p.latitude) * 1000) % 54)}%` }} title={names[p.vehicle_id] || 'Vehicle'}><span>▰</span></div>)}{!positions.length && <div className="map-empty"><span>◎</span><strong>{connected ? 'Waiting for telemetry' : 'Live map offline'}</strong><small>Connect a registered device to see vehicles here</small></div>}<div className="map-controls"><button>＋</button><button>−</button><button>⌖</button></div></div> }
function VehicleTable({ vehicles, positions }) { const online = new Set(positions.map(p => p.vehicle_id)); return <div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Status</th><th>Protocol</th><th>Last seen</th><th /></tr></thead><tbody>{vehicles.length ? vehicles.map(v => <tr key={v.id}><td><span className="vehicle-avatar">{v.name.slice(0, 1)}</span><strong>{v.name}</strong><small>{v.license_plate || v.imei}</small></td><td><span className={`pill ${online.has(v.id) ? 'green' : 'gray'}`}><i />{online.has(v.id) ? 'Moving' : 'Offline'}</span></td><td>{v.protocol === 'teltonika' ? 'FMB920' : 'CONCOX V5'}</td><td>{v.last_seen_at ? new Date(v.last_seen_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Never'}</td><td>•••</td></tr>) : <tr><td colSpan="5"><Empty text="No vehicles registered yet." /></td></tr>}</tbody></table></div> }
function AlertRow({ alert }) { return <div className="alert-row"><span className={`alert-icon ${alert.kind}`}>{alert.kind === 'overspeed' ? '!' : '⌖'}</span><div><strong>{alert.kind.replace('_', ' ')}</strong><p>{alert.message}</p></div><time>{new Date(alert.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div> }
function Pulse({ value, label, color }) { return <div className="pulse-row"><div className={`ring ${color}`} style={{ '--value': `${value * 3.6}deg` }}><strong>{value}<small>%</small></strong></div><span>{label}</span><b>↗</b></div> }
function Empty({ text }) { return <div className="empty">{text}</div> }

function SectionView({ section, vehicles, drivers, trips, alerts, positions, names, reload }) { const data = section === 'Drivers' ? drivers : section === 'Trips & dispatch' ? trips : section === 'Safety' ? alerts : vehicles; const [showForm, setShowForm] = useState(false); return <div className="section-view"><div className="section-toolbar"><div className="search">{icon('search')}<input placeholder={`Search ${section.toLowerCase()}...`} /></div><div className="toolbar-actions">{section === 'Devices' && <button className="primary" onClick={() => setShowForm(true)}>+ Add device</button>}<button className="ghost refresh" onClick={reload}>Refresh <span>↻</span></button></div></div>{section === 'Live fleet' ? <div className="panel full-map"><FleetMap positions={positions} names={names} connected /><VehicleTable vehicles={vehicles} positions={positions} /></div> : section === 'Devices' ? <div className="panel data-panel"><div className="data-header"><p className="eyebrow">GPS DEVICES & VEHICLES</p><h2>{vehicles.length} registered devices</h2><p className="subcopy">Add tracker IMEIs here, then point the device at TCP port 5001 for FMB920 or 5002 for CONCOX V5.</p></div><VehicleTable vehicles={vehicles} positions={positions} /></div> : <div className="panel data-panel"><div className="data-header"><div><p className="eyebrow">{section.toUpperCase()}</p><h2>{data.length} records</h2></div></div>{data.length ? <div className="data-cards">{data.map(item => <div className="data-card" key={item.id}><span className="card-symbol">{section === 'Drivers' ? '♙' : section === 'Safety' ? '!' : section === 'Trips & dispatch' ? '⌁' : '⌖'}</span><div><strong>{item.name || item.reference || item.kind}</strong><p>{item.message || item.destination || item.phone || item.license_plate || 'Active fleet record'}</p></div><span className="card-id">#{item.id}</span></div>)}</div> : <Empty text={`No ${section.toLowerCase()} to display yet.`} />}</div>}{showForm && <DeviceModal onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); reload() }} />}</div> }

function DeviceModal({ onClose, onCreated }) { const [form, setForm] = useState({ name: '', imei: '', license_plate: '', protocol: 'teltonika' }); const [error, setError] = useState(''); const submit = async e => { e.preventDefault(); try { await request('/api/v1/vehicles', { method: 'POST', body: JSON.stringify(form) }); onCreated() } catch (err) { setError(err.message) } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">REGISTER HARDWARE</p><h2>Add a device</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><p className="subcopy">Register the IMEI before powering on the tracker.</p><label>Vehicle name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Delivery van 01" /></label><label>IMEI number<input required minLength="8" value={form.imei} onChange={e => setForm({ ...form, imei: e.target.value.replace(/\D/g, '') })} placeholder="356307042441234" /></label><label>License plate<input value={form.license_plate} onChange={e => setForm({ ...form, license_plate: e.target.value })} placeholder="MH 12 AB 1234" /></label><label>Protocol<select value={form.protocol} onChange={e => setForm({ ...form, protocol: e.target.value })}><option value="teltonika">Teltonika FMB920 · TCP 5001</option><option value="gt06">CONCOX V5 / GT06 · TCP 5002</option></select></label>{error && <div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary">Register device <span>→</span></button></div></form></div> }

createRoot(document.getElementById('root')).render(<App />)
